const arrayOfUsers = [
	{
		username: "andres12",
		name: "Andres",
		lastname: "Gomez",
		email: "andres12@gmail.com",
		password: "SSKsods#!#d323",
		birth: 12121976,
		type: "admin",
	},
	{
		username: "carlos33",
		name: "Carlos",
		lastname: "Goma",
		email: "andres1213@gmail.com",
		password: "SSKsods#!djjd323",
		birth: 10121970,
		type: "user",
	},
	{
		username: "mati54",
		name: "Matias",
		lastname: "Sosa",
		email: "matisosa@gmail.com",
		password: "Sjdj$$$//djdj7",
		birth: 21021999,
		type: "user",
	},
	{
		username: "martin7887",
		name: "Martin",
		lastname: "Martinez",
		email: "marto27@gmail.com",
		password: "Gsksek#$%jd7jd#m%4",
		birth: 12121976,
		type: "user",
	},
	{
		username: "pepe78",
		name: "Jose",
		lastname: "Perez",
		email: "jose78@gmail.com",
		password: "alsdlasd&%ma2332M",
		birth: 17011978,
		type: "user",
	},
	{
		username: "manuu55",
		name: "Manuel",
		lastname: "Diaz",
		email: "manu44@gmail.com",
		password: "KlK738j%$%/(dasd",
		birth: 02072001,
		type: "user",
	},
	{
		username: "jose1234",
		name: "Jose",
		lastname: "Fernandez",
		email: "mansdfsdfu44@gmail.com",
		password: "KlK738j%$%/(dasd",
		birth: 26061993,
		type: "user",
	},
];

module.exports = arrayOfUsers;
